### PR TITLE
5368 user stt region assignment validation user group change

### LINKED ISSUE #5368: [BUG] User STT and Region assignment validation on user group change
### Description

User group is allowed to be changed without validating STT and Region assignment, in the admin page. This is lower impact since user should have access to admin page (only impacting OFA admin users who are allowed to change user groups.

### Action Taken

Login to admin page, assigned a user to "Regional Staff" and assign a region to this user. Then save and try to change the user group to OFA admin. Confirm that you can save the user without any error.

Image

Image

### What I expected to see

See the error: "Users other than Regional Staff, Developers, Data Analysts do not get assigned a location"

Note: Idea is to create a validation that correctly validates user group and location assignment for both DRF and Admin page. This should be possibly done using validation function in _model_.

### What I did see

User group was successfully changed

### Other Helpful Information

+ URL of the page I was on:
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

### Usability Testing Criteria 
_PM/UX/OFA Only: Create a list of expected user behaviors that should be confirmed when UX and/or PM is testing this ticket_
- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_

### PR DESCRIPTION
**Pull request by raftmsohani**
## Summary of Changes

Pull request closes #5368 _

Originally the ticket was written to consolidate user/region validation for DRF and AdminForm into one validation. 

There were a couple of issues existing:
1. One problem was that region was being validated ahead and separate from user model. This was because the region model was resented in the admin model through an inline formset. Formsets do not allow to related the form field from the related model, so it was not possible to cross validate region against user and it's group set.
2. When trying to combine DRF validation with model validation, we were losing a lot of capability django and django DRF offer. 

As a result, it was decided to keep the validation for DRF vs admin form separate.

## How to Test
_List the steps to test the PR_
These steps are generic, please adjust as necessary.
```
cd tdrs-frontend && docker-compose up --build
cd tdrs-backend && docker-compose up --build
```

1. Open http://localhost:3000/ and sign in.
1. Go to user admin page and open one of the user details
2. click on the group "ACF ACIO" check that Region settings disappears
3. click on the group "DEVELOPER" and check that settings appears
4. Check that you cannot assign region to non-regional staff

User now sees this message when trying to assign region to non-regional staff:

Screenshot 2025-10-20 at 9 16 25 PM

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by elipe17 — CHANGES_REQUESTED** [review]
Lets talk about this in office hours tomorrow. This doesn't remedy the primary issue of a brand new user requesting regions and then an admin being unable to assign a group because of the validation. I think we talked about just forcing the user's group to regional staff to prevent this deadlock. But lets confirm in OH.

**Comment by raftmsohani** [comment]
> Lets talk about this in office hours tomorrow. This doesn't remedy the primary issue of a brand new user requesting regions and then an admin being unable to assign a group because of the validation. I think we talked about just forcing the user's group to regional staff to prevent this deadlock. But lets confirm in OH.

In fact it does, if user initially requests a region, then admin can still assign a group. 

However, it has another bug: since we are hiding the regions field in case of non-regional, then suer has to first choose regional -> delete region -> then assign the group.  Let's discuss in OH today

File: tdrs-backend/tdpservice/users/static/admin/js/user_form_region_toggle.js [hunk 1]
```diff
@@ -0,0 +1,20 @@
...
+
+    function toggleRegionField() {
+        if (!groupSelect || !regionFieldRow) return;
+
+        const selectedOptions = Array.from(groupSelect.selectedOptions).map(opt => opt.textContent.trim());
+        const regionalRoles = ["OFA Regional Staff", "Developer", "Data Analyst"];
+
+        const hasRegionalRole = selectedOptions.some(role => regionalRoles.includes(role));
+
+        regionFieldRow.style.display = hasRegionalRole ? '' : 'none';
```
Comment (elipe17) [inline tdrs-backend/tdpservice/users/static/admin/js/user_form_region_toggle.js]: If a user requests regional access, the regions don't show up unless a appropriate group is selected. This makes it challenging for approving admins to know what group should be assigned to a user. Can we make the element visible but not enabled until a appropriate group is selected? An explainer saying something like "the user has requested regions, please assign a appropriate group to be able to edit their selections." would also be really helpful.

File: tdrs-backend/tdpservice/users/static/admin/js/user_form_region_toggle.js [hunk 2]
```diff
@@ -0,0 +1,20 @@
+document.addEventListener('DOMContentLoaded', function() {
+    const groupSelect = document.querySelector('#id_groups');
+    const regionFieldRow = document.querySelector('#id_regions').closest('.form-row, .field-box, .form-group');
+
+    function toggleRegionField() {
+        if (!groupSelect || !regionFieldRow) return;
+
+        const selectedOptions = Array.from(groupSelect.selectedOptions).map(opt => opt.textContent.trim());
+        const regionalRoles = ["OFA Regional Staff", "Developer", "Data Analyst"];
```
Comment (elipe17) [inline tdrs-backend/tdpservice/users/static/admin/js/user_form_region_toggle.js]: Data Analyst will never be assigned regions.

```suggestion
        const regionalRoles = ["OFA Regional Staff", "Developer"];
```

File: tdrs-backend/tdpservice/users/constants.py [hunk 3]
```diff
@@ -0,0 +1,3 @@
+"""Constants for user roles and permissions."""
+
+REGIONAL_ROLES = {"OFA Regional Staff", "Developer", "Data Analyst"}
```
Comment (elipe17) [inline tdrs-backend/tdpservice/users/constants.py:3]:
```suggestion
REGIONAL_ROLES = {"OFA Regional Staff", "Developer"}
```

**Review by elipe17 — CHANGES_REQUESTED** [review]
See my comments. OFA Regional Request Access is working great now though!

File: tdrs-backend/tdpservice/users/forms.py [hunk 4]
```diff
@@ -0,0 +1,86 @@
...
+        required=False,
+        widget=admin.widgets.FilteredSelectMultiple("Regions", is_stacked=False),
+    )
+
+    delete_regions = forms.BooleanField(
+        label="Delete Regions?",
+        required=False,
+        help_text="Check this box to trigger region deletion. This action is useful when changing user groups."
+        + " It ensures that regions are reset according to the new group assignments. Uncheck to retain existing regions."
+        + " If group is regional staff, then this button is not shown and region manupulation has to be done through the regions field."
```
Comment (elipe17) [inline tdrs-backend/tdpservice/users/forms.py]: This text is a little misleading since it shows up as long as I am a regional role. 

Also, If I check the field as a regional user to remove all my regions and save then nothing happens.  I think that is the intended state?

If I change my group and have this selected I get the regional validation error.
Screenshot 2025-10-30 at 11 56 02 AM
Screenshot 2025-10-30 at 11 56 07 AM

Comment (raftmsohani) [reply tdrs-backend/tdpservice/users/forms.py]: @elipe17 so I have removed "Delete Regions" as an option, because I thought the user should be able to remove the regions from the form.
Also, the validation in User model was a blocker when changing user groups. So moved it out to .save(), and then as a result had to:
1. Add validation to User form
2. Add validation to API to serializer

File: tdrs-backend/tdpservice/conftest.py [hunk 5]
```diff
@@ -162,7 +162,7 @@ def digit_team(stt):
     user = UserFactory.create(
         groups=(Group.objects.get(name="DIGIT Team"),),
     )
-    user.stt = stt
```
Comment (raftmsohani) [inline tdrs-backend/tdpservice/conftest.py:165]: this was already wrong. DIGIT Team should not be assigned location.

**Comment by raftmsohani** [comment]
Two e2e tests are failing in cypress, because User is trying to add location on their user profile, which is not allowed by user serializer, so the user get's 400 when adding location.

File: tdrs-backend/tdpservice/users/constants.py (hunk 3 above)
Comment (elipe17) [inline tdrs-backend/tdpservice/users/constants.py:3]: Data analyst should not be allowed to have regions

File: tdrs-backend/tdpservice/users/serializers.py [hunk 6]
```diff
@@ -168,57 +167,46 @@ def get_pending_requests(self, obj):
...
+        groups = self.instance.groups.all()
+        regions = validated_data.get('regions')
+        stts = validated_data.get('stt')
+        # Check if the user belongs to any regional group
+        if groups:
+            has_regional_role = any(g.name in REGIONAL_ROLES for g in groups)
+        else:
+            has_regional_role = False
+
+        if has_regional_role and not (regions or stts):
```
Comment (elipe17) [inline tdrs-backend/tdpservice/users/serializers.py]: Why does this allow stts?  This seems to me like the validation would pass if the user was a Regional Staff and had regions or an stt. But if it is a regional user it should not have an stt

File: tdrs-backend/tdpservice/users/views.py [hunk 7]
```diff
@@ -96,16 +97,50 @@ def request_access(self, request):
...
+        )  # DRF ignores commit, but semantically clearer
+        for field, value in serializer.validated_data.items():
+            try:
+                if not field == "regions":  # M2M handled separately
+                    setattr(instance, field, value)
+            except AttributeError as e:
+                logger.error(
+                    "Failed to set attribute %s on user %s: %s", field, user.id, e
+                )
+        instance.save()
```
Comment (elipe17) [inline tdrs-backend/tdpservice/users/views.py:122]: This seems to not be having an effect and is preventing users from requesting access. See the attached video.

https://github.com/user-attachments/assets/bf98741c-4165-42e6-abce-d1a3f65eb468

**Review by elipe17 — CHANGES_REQUESTED** [review]
See my feedback

File: tdrs-backend/tdpservice/users/constants.py (hunk 3 above)
Comment (raftmsohani) [reply tdrs-backend/tdpservice/users/constants.py:3]: REGIONAL here is more of the line: can have location. This is coming from what we had originally in the model. But we can definitely separate them

File: tdrs-backend/tdpservice/users/serializers.py (hunk 6 above)
Comment (raftmsohani) [reply tdrs-backend/tdpservice/users/serializers.py]: again it means the user can have location, and data_analyst is in there so that during registration user can register with an STT assigned

File: tdrs-backend/tdpservice/users/views.py (hunk 7 above)
Comment (raftmsohani) [reply tdrs-backend/tdpservice/users/views.py:122]: interesting, tested myself and user is saved just fine. I will try with a couple of more users, but would like to see what error you are getting.

**Review by elipe17 — APPROVED** [review]
Nice job sir. LGTM!

**Review by jtimpe — APPROVED** [review]
