### PR TITLE
3141 - fix cypress

### LINKED ISSUE #3141: test-deployment-e2e is failing integration test
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description
For weeks/months, develop environment fails our e2e cypress test. I can't find origin of when it failed.

## Action Taken
Upon merge of successful and tested branch to develop, e2e test fails.

## What I expected to see

Screenshot 2024-08-13 at 12 56 11 PM

## What I did see

Test failure in develop
Screenshot 2024-08-13 at 12 54 06 PM

## Other Helpful Information

+ URL of the page I was on: https://app.circleci.com/pipelines/github/raft-tech/TANF-app/27222/workflows/a9ff2e6c-1901-4684-b51d-83c946e7a4e7/jobs/80249
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know )
+ Has the issue occurred more than once?:

### PR DESCRIPTION
**Pull request by jtimpe**
## Summary of Changes
Pull request closes #3141 
* fix cypress e2e tests logging in as the wrong user. Two parts to this
   1. call `cy.visit('/')` before `adminLogin`, so that the page is first accessed from a logged-out state
   2. call `cy.clearcookies()` before `cy.visit('/')` on regular-user login, so that any cookies grabbed from `adminLogin` are removed

## How to Test
1. Open `cypress.config.js` and make the following changes
   ```javascript
   baseUrl: 'https://tdp-frontend-raft.app.cloud.gov',
   env: {
     apiUrl: 'https://tdp-frontend-raft.app.cloud.gov/v1',
     adminUrl: 'https://tdp-frontend-raft.app.cloud.gov/admin',
     cypressToken: '',  // get this from cloud.gov env (or reach out to me)
   }
   ```
3. Run
   ```bash
   cd ./tdrs-frontend
   npm run test:e2e
   ```

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] Fix tests
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by andrew-jameson — APPROVED** [review]

File: tdrs-frontend/cypress/e2e/common-steps/common-steps.js [hunk 1]
```diff
@@ -1,38 +1,44 @@
 import { When } from '@badeball/cypress-cucumber-preprocessor'
 
 When('{string} visits the home page', (username) => {
```
Comment (raftmsohani) [inline tdrs-frontend/cypress/e2e/common-steps/common-steps.js:3]: can't we store the admin and user separately and use them from store as necessary, instead of deleting them?

**Review by raftmsohani — APPROVED** [review]
LGTM only have a question but the solution works

**Review by elipe17 — APPROVED** [review]

File: tdrs-frontend/cypress/e2e/common-steps/common-steps.js (hunk 1 above)
Comment (ADPennington) [reply tdrs-frontend/cypress/e2e/common-steps/common-steps.js:3]: @jtimpe 🆙

**Comment by ADPennington** [comment]
confirmed with @jtimpe that this is fixing an issue on develop branch only. bypassing qasp. please feel free to merge when ready 😄

File: tdrs-frontend/cypress/e2e/common-steps/common-steps.js (hunk 1 above)
Comment (jtimpe) [reply tdrs-frontend/cypress/e2e/common-steps/common-steps.js:3]: this is technically what's being done already via the following calls in `cypress/support/commands.js`

```js
// regular login
cy.getCookie('sessionid').its('value').as('userSessionId')
cy.getCookie('csrftoken').its('value').as('userCsrfToken')

// admin login
cy.getCookie('sessionid').its('value').as('adminSessionId')
cy.getCookie('csrftoken').its('value').as('adminCsrfToken')
```

this takes the value from the cookie immediately after login and stores it in the cypress intermediary variable, which lives for the test run. So the `cy.clearCookie` and `cy.setCookie` apply to the browser window during the test run and use the stored values.

We should do better caching of the vars so that we don't have to re-login both users before *every* test, but that's covered in a followup ticket #3274
