### PR TITLE
Rapid File Submission Bug

### LINKED ISSUE #4897: Bug: Rapid clicking of the submit button submits multiple copies of the file
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that something isn't working the way one would expect it to work. Please provide us with the information requested below and we will look at it as soon as we are able.

### Description

Clicking the **Submit Report** button multiple times before the submission history loads can result in multiple copies of the same file being submitted. This causes confusion in the submission history view, where duplicate submissions appear.

### Action Taken

During the 4/16 early access session, we tested submitting an FRA file. By clicking the **Submit Report** button rapidly (before the submission history section updated), we were able to submit the same file up to four times in a single attempt.

### What I expected to see

A single submission entry in submission history, regardless of how many times the submit button was clicked.

### What I did see

Multiple identical submissions appeared in the submission history, despite having uploaded only one file and intending to submit it once.

### Other Helpful Information

+ **URL of the page I was on:** [Include the specific page URL here]  
+ **Browser and version:** [e.g., Chrome 123.0.0.0]  
+ **Operating System:** MacOS X  
+ **Is the issue repeatable?:** yes  
+ **Has the issue occurred more than once?:** yes  

### Usability Testing Criteria  
- [ ] Attach an FRA file
- [ ] Click submit rapidly
- [ ] Confirm only one version is submitted

---

### Notes

Given the speed of submission state updates, visual or audio changes to the button are not necessary. A simple guardrail to prevent rapid multi-click submission is sufficient—no need to update the button’s appearance or use an `aria-disabled` state.

### Supporting Documentation

Screenshot of issue

### PR DESCRIPTION
**Pull request by elipe17**
## Summary of Changes
- Added custom hook to try and make form submission and submission loading more generic
- Added logic for both the TANF and FRA data files page to prevent a user from submitting forms multiple times while the request is still pending via the new hook
- Added a submitting indicator to button to keep user informed about what's happening

Pull request closes #4897 

## How to Test
```
cd tdrs-frontend && docker-compose up --build
cd tdrs-backend && docker-compose up --build
```

1. Open http://localhost:3000/ and sign in.
2. Go to either of the datafiles page
3. In the developer tools of the browser, change your network speed to something really slow
4. Upload a file
5. Submit the file and verify the submission button cannot be clicked again and reads `Submittting...`

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] Multiple submissions of the same file cannot occur when rapidly clicking submit
+ [ ] User sees indicator that files are being submitted

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [ ] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

**Review by raftmsohani — APPROVED** [review]
LGTM!

File: tdrs-frontend/src/hooks/useFormSubmission.js [hunk 1]
```diff
@@ -0,0 +1,55 @@
...
+    } finally {
+      // Reset submitting state
+      setIsSubmitting(false)
+    }
+  }
+
+  return {
+    isSubmitting,
+    executeSubmission,
+    onSubmitStart: () => setIsSubmitting(true),
```
Comment (jtimpe) [inline tdrs-frontend/src/hooks/useFormSubmission.js:52]: what's the intention behind the callbacks? i don't see them used, can they be removed?

**Review by jtimpe — APPROVED** [review]
Good work! Love the hooks/hof pattern

File: tdrs-frontend/src/hooks/useFormSubmission.js (hunk 1 above)
Comment (elipe17) [reply tdrs-frontend/src/hooks/useFormSubmission.js:52]: They are being used in the FRAReports component. But I don't think they need to be exported since the exec callback handles the state. Let me do some testing and see if I can make it simpler :)

**Review by lhuxraft — APPROVED** [review]
@elipe17 I love the way this looks and how you've updated the button during submission! LGTM 🚀

**Review by victoriaatraft — APPROVED** [review]
LGTM. The submitting button is quick even when simulating a slower speed but still works! Just an observation -- I can select `change file` and select the same file and resubmit.
