### PR TITLE
[BUGFIX] revert REDIS_URI back to using django's CELERY_BROKER_URL setting

### LINKED ISSUE #5673: Celery metrics unavailable - REDIS_URI missing TLS scheme and database number
### Description

Celery prometheus metrics endpoint is unresponsive across all environments.

Root cause: In `celery_start.sh`, the `REDIS_URI` was changed from using Django's computed `CELERY_BROKER_URL` setting to pulling the raw URI directly from `VCAP_SERVICES`. The raw VCAP_SERVICES URI:

1. Uses `redis://` instead of `rediss://` (missing TLS)
2. Does not include the database number suffix (e.g., `/0`, `/3`, `/6`)

The database number is critical because environments sharing a Redis instance (e.g., raft/qasp/a11y in dev) use different database numbers to avoid collisions, as computed by `get_cloudgov_broker_db_numbers()` in `tdpservice/common/util.py`.

### Cause

The line in `celery_start.sh` was changed from:
```bash
REDIS_URI=$(python manage.py shell -c "from django.conf import settings; print(settings.CELERY_BROKER_URL)" 2>/dev/null)
```
to:
```bash
REDIS_URI=$(echo $VCAP_SERVICES | jq -r '."aws-elasticache-redis"[0].credentials.uri')
```

This caused the celery-exporter to attempt a plain TCP connection to a TLS-expecting Redis endpoint with no database selected, causing it to hang indefinitely when serving `/metrics`.

### What I expected to see

Prometheus successfully scraping celery metrics from all environments. Celery-related Grafana dashboards populated with data.

### What I did see

All celery Prometheus targets show `DOWN`:
```
Endpoint: http://tdp-celery-raft.apps.internal:9808/metrics
State: DOWN
Error: Get "http://tdp-celery-raft.apps.internal:9808/metrics": context deadline exceeded
Scrape Duration: 10.0s
```

The celery-exporter process is running and listening on port 9808, but hangs when queried because it cannot communicate with Redis.

### Other Helpful Information

+ Affected environments: All (raft, qasp, develop, staging, prod)
+ Is the issue repeatable?: yes
+ Has the issue occurred more than once?: yes — persistent across all environments

### Fix

Revert `celery_start.sh` line 7 back to using the Django-computed `CELERY_BROKER_URL`:
```bash
REDIS_URI=$(python manage.py shell -c "from django.conf import settings; print(settings.CELERY_BROKER_URL)" 2>/dev/null)
```

This ensures the URI includes the correct TLS scheme (`rediss://`) and the environment-specific database number.

### Usability Testing Criteria
- [ ] After fix is deployed, verify `curl localhost:9808/metrics` returns metrics inside each celery container
- [ ] Verify all celery Prometheus targets show `UP` in Prometheus UI
- [ ] Verify Grafana celery dashboards are populated with metrics data
- [ ] Verify celery workers are using the correct database numbers per environment (raft=0, qasp=3, a11y=6, etc.)

### PR DESCRIPTION
**Pull request by mattcoleanderson**
## Summary of Changes

Pull request closes #5673

Fixes the `REDIS_URI` construction in `celery_start.sh`. The previous approach pulled the raw URI from `VCAP_SERVICES` via `jq`, which was missing the `rediss://` TLS scheme and the environment-specific Redis database number. This caused the celery-exporter to hang when querying Redis, making Prometheus metrics unavailable across all environments.

The fix constructs the URI by:
1. Extracting Redis host, port, and password from `VCAP_SERVICES` via `jq` with the `rediss://` TLS scheme
2. Determining the correct database number by calling `get_cloudgov_broker_db_numbers()` from `tdpservice.common.util` directly (avoiding a full Django startup via `manage.py shell`)

Also adds validation and logging to make future Redis connection issues easier to diagnose.

## How to Test

This is an infrastructure/deployment change that cannot be fully tested locally. Verification must happen in Cloud.gov environments.

1. Deploy the change to a dev environment (e.g., raft)
2. SSH into the celery container: `cf ssh tdp-celery-raft`
3. Verify the celery-exporter is responding:
   ```
   curl -s http://localhost:9808/metrics | head
   ```
5. Verify Grafana celery dashboards are populated with metrics in the Uptime/Health dashboard
    - Will still show a firing alert until the uptime has reached 80%
    - All that matters is that Uptime (Celery) shows an a percentage instead of `No Data`
    
image

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] Celery-exporter serves metrics on port 9808 without hanging
+ [ ] All Prometheus celery targets show `UP`
+ [ ] Grafana celery dashboards display metrics data
+ [ ] Each environment uses the correct Redis database number (raft=0, qasp=3, a11y=6, develop=0, staging=3, prod=0)
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] N/A — Shell script change only. The underlying logic (`get_cloudgov_broker_db_numbers`) is already tested in `tdpservice/common/test/test_util.py`.
  + [x] No frontend changes.
+ Are code coverage minimums met?
  + [x] No new code to cover — shell script change only.

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] No backend Python changes — linting N/A.
+ [x] No frontend changes — linting N/A.
+ [x] URI is now constructed correctly with TLS and environment-specific DB numbers, matching `cloudgov.py` logic.

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [x] N/A — No UI changes.

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Comments in `celery_start.sh` explain the URI construction and why the Python utility function is called directly.
+ [x] No new dependencies introduced.

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [x] This fix restores TLS (`rediss://`) for the celery-exporter's Redis connection, which is a security improvement over the broken `redis://` plain-text connection.

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

+ [x] N/A — Infrastructure bugfix, no user-facing changes.

### CODE REVIEW

File: tdrs-backend/celery_start.sh [hunk 1]
```diff
@@ -3,20 +3,46 @@
 echo "Starting celery"
 
 if [[ $1 == "cloud" ]]; then
-    # Get the computed URI from VCAP_SERVICES
-    REDIS_URI=$(echo $VCAP_SERVICES | jq -r '."aws-elasticache-redis"[0].credentials.uri')
+    # Build the broker URL with TLS scheme and correct DB number (matching cloudgov.py logic)
+    REDIS_BASE=$(echo $VCAP_SERVICES | jq -r '."aws-elasticache-redis"[0].credentials | "rediss://:\(.password)@\(.host):\(.port)"')
```
Comment (raftmsohani) [inline tdrs-backend/celery_start.sh:7]: nit: add missing credit value handling

**Review by elipe17 — APPROVED** [review]
LGTM

File: tdrs-backend/celery_start.sh (hunk 1 above)
Comment (mattcoleanderson) [reply tdrs-backend/celery_start.sh:7]: The error handling is on line 17. If the credentials are missing, an error is logged and the script exits.

https://github.com/raft-tech/TANF-app/blob/d2645ca6aa8a12cb875fc9a23f73b8eb84b9b73e/tdrs-backend/celery_start.sh#L17-L20

**Review by jtimpe — APPROVED** [review]

**Review by raftmsohani — APPROVED** [review]
