### PR TITLE
Fix screenreader interruption when parsing complete banner appears

### LINKED ISSUE #5584: "Parsing Complete" banner interrupts screenreader reading of "Successfully Submitted"
### Description

When using a screenreader on the TANF datafiles page, the "Successfully Submitted" banner reading is interrupted by "Parsing Complete" when parsing is very short. The banner itself replaces very quickly visually, but for screenreaders this is an accessibility issue.

### Action Taken

* Navigate to TANF data files.
* Select a section 3 or 4 file (since they are very short) and click submit.
* Notice that "Successfully Submitted" is nearly immediately replaced with "Parsing Complete."
* Using a screenreader, perform the same steps and notice the reading of "Successfully Submitted" is interrupted.

### What should happen

These suggestions from @reitermb 
* ~~Remove the "Parsing Complete" banner completely. In a future ticket, the TANF Data Files page will no longer have the Submission History tab (matching the FRA page) and the banner would be irrelevant; or,~~
* ~~Change "Parsing" to "Processing" and change element `aria` arrangements such that "Processing Complete" reads after "Successfully Submitted," rather than interrupting (make the first banner an `aria-live` region, and append the second message to that region); or,~~
* Change "Parsing" to "Processing" and make "Processing Complete" into a completely separate banner, with both banners set to `aria-polite`, which should make them read out sequentially.

### What I did see

* The "Successfully Submitted" banner is nearly immediately replaced with "Parsing Complete."
* Using a screenreader, the reading of the "Successfully Submitted" banner is interrupted.

### Other Helpful Information

+ URL of the page I was on: `/tanf-data-files`
+ Browser and version:
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: yes
+ Has the issue occurred more than once?: yes

### Usability Testing Criteria 
_PM/UX/OFA Only: Create a list of expected user behaviors that should be confirmed when UX and/or PM is testing this ticket_
- [ ] _Outcome 1_
- [ ] _Outcome 2_
- [ ] _Outcome 3_

### PR DESCRIPTION
**Pull request by mattcoleanderson**
## Summary of Changes
This PR fixes an accessibility issue where the "Parsing Complete" banner was interrupting the screenreader while it was reading the "Successfully Submitted" banner message.

Pull request closes #5584

### What Changed

**Before:** A single alert banner that displayed "Successfully submitted..." and was then immediately replaced with "Parsing complete." - causing the screenreader to be interrupted mid-sentence.

**After:** Two separate banners that display simultaneously:
1. **localAlert banner** - Shows "Successfully submitted section: [section] on [date]"
2. **processingAlert banner** - Shows "Processing complete." (renamed from "Parsing complete")

Both banners remain visible, allowing users to see both messages. For screenreaders, the messages queue up and are read sequentially without interruption.

### Technical Implementation

**1. New processingAlert state** - Added alongside the existing localAlert in `ReportsContext.jsx`:
- Separate state object: `{ active, type, message }`
- Separate ref for scroll behavior
- Clears when user changes: file selection, year, quarter, file type, or STT

**2. Dual banner UI pattern** - Applied to all file upload forms:
- `SectionFileUploadForm.jsx` (TANF data files)
- `QuarterFileUploadForm.jsx` (Program Integrity Audit files)
- `FRAReports.jsx` (FRA reports)

**3. Accessibility pattern** - Separates screen-reader content from visible UI:
```jsx
{/* Screen-reader announcer (visually hidden) */}
<div className="usa-sr-only">
  <div role="status" aria-live="polite" aria-atomic="true">
    {localAlert.active ? localAlert.message : ''}
  </div>
  <div role="status" aria-live="polite" aria-atomic="true">
    {processingAlert.active ? processingAlert.message : ''}
  </div>
</div>

{/* Visible alerts (hidden from accessibility tree) */}
{localAlert.active && (
  <div className="usa-alert..." aria-hidden="true">...</div>
)}
{processingAlert.active && (
  <div className="usa-alert..." aria-hidden="true">...</div>
)}
```

**Why this pattern works:**
- `usa-sr-only`: Visually hidden but available to screenreaders
- `role="status"` + `aria-live="polite"`: Queues announcements without interrupting
- `aria-atomic="true"`: Announces entire content when changed
- `aria-hidden="true"` on visible alerts: Prevents duplicate announcements

### Files Modified
| File | Change |
|------|--------|
| `ReportsContext.jsx` | Added `processingAlert` state, `setProcessingAlertState`, `processingAlertRef`; clears on year/quarter/fileType/STT change |
| `useFileUploadForm.js` | Exposes `processingAlert` state and setter; shows "Processing complete." instead of overwriting localAlert |
| `SectionFileUploadForm.jsx` | Dual banner UI + sr-only pattern |
| `QuarterFileUploadForm.jsx` | Dual banner UI + sr-only pattern |
| `FRAReports.jsx` | Dual banner UI + sr-only pattern; separate scroll-to effect for processingAlert |
| `FileUpload.jsx` | Clears both alerts when file selection changes |

## How to Test
```
cd tdrs-frontend && docker-compose up --build
```

1. Open http://localhost:3000/ and sign in
2. Navigate to TANF Data Files page
3. Select a Section 3 or 4 file (short parsing time) and submit
4. **Visual verification**: 
   - See "Successfully submitted section: [X] on [date]" banner appear
   - See "Processing complete." banner appear below it (both remain visible)
5. **Screenreader verification** (with NVDA, VoiceOver, or JAWS):
   - Both messages are read sequentially without the first being interrupted
6. **Clear behavior**: Select a different file - both banners should disappear

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] Screenreader reads "Successfully Submitted" message completely before "Processing Complete" message
+ [ ] Both banners display correctly to visual users (two separate banners visible)
+ [ ] Processing alert clears when a new file is selected
+ [ ] Processing alert clears when year/quarter/file type is changed
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [ ] If this PR introduces backend code changes, are they meaningfully tested?
  + [x] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [ ] Backend coverage: N/A - no backend changes

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [ ] Are backend code style checks passing on CircleCI?
+ [ ] Are frontend code style checks passing on CircleCI?
+ [ ] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [ ] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [x] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [ ] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

N/A - This is a bug fix based on existing accessibility requirements.

### CODE REVIEW

**Review by elipe17 — APPROVED** [review]
Worked as expected. LGTM

**Review by jtimpe — APPROVED** [review]

**Comment by raftmsohani** [comment]
the code removes the effect that clears the file input + preview when year/quarter (or file type) changes, is that intentional? I thought we have another ticket to perform this since we will need to recheck the file with new year/quarter change

**Review by victoriaatraft — APPROVED** [review]
Screenreader did read the confirmation banners upon upload. 
I did notice that I'm unable to navigate to the banners and/or have a focus state on the banners themselves. @mattcoleanderson @reitermb

File: tdrs-frontend/src/components/Reports/FRAReports.jsx [hunk 1]
```diff
@@ -730,10 +741,10 @@ const FRAReportsContent = () => {
                 datafile: response?.data,
               },
             })
-            setLocalAlertState({
```
Comment (raftmsohani) [inline tdrs-frontend/src/components/Reports/FRAReports.jsx:743]: FRA success is still using "setLocalAlertState" with parsing complete instead of new processingAlert

Comment (raftmsohani) [reply tdrs-frontend/src/components/Reports/FRAReports.jsx:743]: see this: https://github.com/raft-tech/TANF-app/blob/f5bcb45225bb4e5a9d56b4d9e5818832195b87d3/tdrs-frontend/src/components/Reports/FRAReports.jsx#L665

**Comment by mattcoleanderson** [comment]
> the code removes the effect that clears the file input + preview when year/quarter (or file type) changes, is that intentional? I thought we have another ticket to perform this since we will need to recheck the file with new year/quarter change

@raftmsohani I'm not really sure why you think it was removed. This code doesn't touch the input elements at all, just the banner logic. And after looking into it, the input/preview behave the same on this branch as develop for me

**Comment by mattcoleanderson** [comment]
> Screenreader did read the confirmation banners upon upload. I did notice that I'm unable to navigate to the banners and/or have a focus state on the banners themselves.

@victoriaatraft This was intentional as a workaround to get sequential messages working properly. Instead of screen readers announcing the visual alert banners, the banners are set to `aria-hidden="true"` and the announcement is done from a non-visual `usa-sr-only` div. This solves an issue, where the screen reader was dictating the alerts twice, but does mean that the banners are not focusable by the screen reader.

Will this be an issue from an accessibility perspective?

File: tdrs-frontend/src/components/Reports/FRAReports.jsx (hunk 1 above)
Comment (mattcoleanderson) [reply tdrs-frontend/src/components/Reports/FRAReports.jsx:743]: Fixed

**Comment by victoriaatraft** [comment]
> > Screenreader did read the confirmation banners upon upload. I did notice that I'm unable to navigate to the banners and/or have a focus state on the banners themselves.
> 
> @victoriaatraft This was intentional as a workaround to get sequential messages working properly. Instead of screen readers announcing the visual alert banners, the banners are set to `aria-hidden="true"` and the announcement is done from a non-visual `usa-sr-only` div. This solves an issue, where the screen reader was dictating the alerts twice, but does mean that the banners are not focusable by the screen reader.
> 
> Will this be an issue from an accessibility perspective?

Ahh okay. It was definitely a nice to have to focus, but it's already great that the screen reader reads the messages.

**Review by victoriaatraft — APPROVED** [review]
