### PR TITLE
3269 [BUGFIX] refactor reparse js file

### LINKED ISSUE #3269: [bug] DAC reparse action confirmation pop-up does not include total # files selected if GT 100 files
Thank you for taking the time to let us know about the issue you found. The basic rule for bug reporting is that 
something isn't working the way one would expect it to work. Please provide us with the information requested 
below and we will look at it as soon as we are able.

## Description

- sys admin selected greater than 100 files to reparse via DAC and the pop-up indicates 100 files were selected for reparsing. 
- after triggering the reparse action button, the logs verify that GT 100 files were selected. 

## Action Taken

- sign-in as sys admin
- navigate to DAC data files page
- select greater than100 files to reparse
- review pop-up 
- pop-up confirmation inconsistent with selections when selecting more than 100 files to reparse via DAC data files page 

## What I expected to see

pop-up indicating 679 files were selected for reparsing
bug1_679

## What I did see

- pop up indicating100 files were selected for reparse

bug2_679

- logentries with evidence of gt 100 (i.e. N=679) files selected for reparse
bug3_679

 - reparse model with evidence of gt 100 (i.e. N=679) files selected for reparse
 
bug4_679

## Other Helpful Information

+ URL of the page I was on:
+ Browser and version: 
+ Operating System: ( Windows | MacOS X | Linux | Other )
+ Is the issue repeatable?: ( yes | no | don't know ) yes
+ Has the issue occurred more than once?:

### PR DESCRIPTION
**Pull request by raftmsohani**
## Summary of Changes
Pull request closes #3269

## How to Test

1. Open http://localhost:3000/ and sign in.
1. Proceed to admin -> datafile
2. You will need more than 500 datafiles to test the functionality. If you are testing this locally, you can create a loop using `backend-exec-seed-db` (you will need to change the script to use multiple STTs in a loop), otherwise test this in dev env 
3. If reparse command is not used, then form will not be submitted. Otherwise if 'reparse' command is chosen, then modal will show the number of files to be reparsed.

## Deliverables
_More details on how deliverables herein are assessed included [here](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverables)._

### [Deliverable 1: Accepted Features](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-1-Accepted-Features)

Checklist of ACs:
+ [ ] [**_insert ACs here_**]
+ [ ] **`lfrohlich`** and/or **`adpennington`**  confirmed that ACs are met.

### [Deliverable 2: Tested Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-2-Tested-Code)

+ Are all areas of code introduced in this PR meaningfully tested?
  + [x] If this PR introduces backend code changes, are they meaningfully tested?
  + [ ] If this PR introduces frontend code changes, are they meaningfully tested?
+ Are code coverage minimums met?
  + [ ] Frontend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)
  + [x] Backend coverage: [_insert coverage %_] (see `CodeCov Report` comment in PR)

### [Deliverable 3: Properly Styled Code](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-3-Properly-Styled-Code)

+ [x] Are backend code style checks passing on CircleCI?
+ [x] Are frontend code style checks passing on CircleCI?
+ [x] Are code maintainability principles being followed?

### [Deliverable 4: Accessible](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-4-Accessibility)

+ [ ] Does this PR complete the epic? 
+ [ ] Are links included to any other gov-approved PRs associated with epic?
+ [ ] Does PR include documentation for Raft's a11y review? 
+ [ ] Did automated and manual testing with `iamjolly` and `ttran-hub` using Accessibility Insights reveal any errors introduced in this PR?

### [Deliverable 5: Deployed](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-5-Deployed)

+ [x] Was the code successfully deployed via automated CircleCI process to development on Cloud.gov?

### [Deliverable 6: Documented](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-6-Code-documentation)

+ [x] Does this PR provide background for why coding decisions were made?
+ [ ] If this PR introduces backend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces frontend code, is that code easy to understand and sufficiently documented, both inline and overall?
+ [ ] If this PR introduces dependencies, are their licenses documented?
+ [x] Can reviewer explain and take ownership of these elements presented in this code review?

### [Deliverable 7: Secure](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-7-Secure)

+ [x] Does the OWASP Scan pass on CircleCI?
+ [ ] Do manual code review and manual testing detect any new security issues?
+ [ ] If new issues detected, is investigation and/or remediation plan documented? 

### [Deliverable 8: User Research](https://github.com/raft-tech/TANF-app/blob/develop/docs/How-We-Work/our-priorities-values-expectations.md#Deliverable-8-User-Research)

Research product(s) clearly articulate(s):
+ [ ] the purpose of the research
+ [ ] methods used to conduct the research 
+ [ ] who participated in the research
+ [ ] what was tested and how
+ [ ] impact of research on TDP
+ [ ] (_if applicable_) final design mockups produced for TDP development

### CODE REVIEW

File: tdrs-backend/tdpservice/data_files/static/admin/js/admin/admin_datafile_model.js [hunk 1]
```diff
@@ -2,29 +2,47 @@ $(window).on('load', function() {
...
-
-          break;
-        }
-    }
     submitBtn.addEventListener('click', function(e) {
         e.preventDefault();
-        if (confirm("You are about to re-parse " + number_of_files.innerHTML.split(/(\s+)/)[0] + " files. Are you sure you want to continue?")) {
-            console.log('submitting');
-            theForm.submit();
+        for (var i = 0; i < theForm.childNodes.length; i++) {
```
Comment (elipe17) [inline tdrs-backend/tdpservice/data_files/static/admin/js/admin/admin_datafile_model.js]: This works as advertised. But is there not a way for us to select the element containing the selected number of files instead of looping through children manually? Could we do something more like: `document.querySelector("span.all");`? I tried in the dev tools to see if it works and it returns the right element. We would just need to split on the space character to extract the number. We would also need to check that the element isn't hidden. If it was, then we just grab the other span.

Comment (elipe17) [reply tdrs-backend/tdpservice/data_files/static/admin/js/admin/admin_datafile_model.js]: Forgot to include the screenshot:

Screenshot 2024-11-14 at 2 16 42 PM

**Review by elipe17 — CHANGES_REQUESTED** [review]
Left a suggestion. Let me know what you think.

**Review by elipe17 — APPROVED** [review]
LGTM!

**Review by andrew-jameson — APPROVED** [review]
LGTM

**Review by ADPennington — APPROVED** [review]
lgtm! 🚀 

reparsegt100files
reparsegt100filesp2
